### ISSUE TITLE
two function problem

### ISSUE THREAD

**Issue by Xinya-liuliu** [Huiyu-Li/Preprocess-of-CT-data#1]
Hello, “generate_subNumber” on line 267 in Preprocess-of-CT-data/CheckPreprocessed.py/ and “saved_preprocessed_testing” on line 186 in Preprocess-of-CT-data/LiTS_Decide_Preprocessing/main.py/ cannot find the specific function definition, can you give the specific definition of these two functions?thanks.

**Comment by Xinya-liuliu** [comment]
> Hello, “generate_subNumber” on line 267 in Preprocess-of-CT-data/CheckPreprocessed.py/ and “saved_preprocessed_testing” on line 186 in Preprocess-of-CT-data/LiTS_Decide_Preprocessing/main.py/ cannot find the specific function definition, can you give the specific definition of these two functions?thanks.

**Comment by lxr-1204** [comment]
Hello，I also encountered the same problem, did you solve it?
